#!/bin/bash

RED='\e[41m'
BLUE='\e[44m'
ORANGE='\e[46m'
NC='\e[0m'
trap 'rm $HOME/{.installed_kernels,.available_kernels} &>/dev/null' EXIT
in_array() {
    local haystack=${1}[@]
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done
    return 1
}

function install_kernel {
PS3="choose a kernel to install (ctrl+d to continue | ctrl+c to quit) "

# Gather the results in an array.
kernels=($(grep -v -f .installed_kernels .available_kernels) "proceed" "cancel")

select pick in "${kernels[@]}"
do
	case $pick in
		proceed)
			break
			;;
		cancel)
			exit
			;;		
		*)	if in_array picks $pick; then
					picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick));	
				else
					picks+=("$pick")
			fi
	        printf 'Selected: %s\n' "${picks[*]}"
			;;		
	esac
done

if [[ $picks ]]; then
    printf 'Installing %s\n' "${picks[*]}"
    sudo mhwd-kernel -i "${picks[@]}"
fi
}

function remove_kernel {
PS3="choose a kernel to remove (ctrl+d to continue | ctrl+c to quit) "
# Gather the results in an array.
kernels=($(grep -v -f .running_kernel .installed_kernels) "proceed" "cancel")

select pick in "${kernels[@]}"
do
	case $pick in
		proceed)
			break
			;;
		cancel)
			exit
			;;		
		*)	if in_array picks $pick; then
					picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick));	
				else
					picks+=("$pick")
			fi
	        printf 'Selected: %s\n' "${picks[*]}"
			;;		
	esac
done

if [[ $picks ]]; then
    printf 'Removing %s\n' "${picks[*]}"
    sudo mhwd-kernel -r "${picks[@]}"
fi
}

mhwd-kernel -li | awk 'NR==1 {print $4}' | tr -d '()' > .running_kernel
mhwd-kernel -li | awk 'NR > 2 { print $2}' > .installed_kernels
mhwd-kernel -l | awk 'NR > 1 { print $2}' > .available_kernels

    while true; do
    clear
    echo ""
    echo -e "                             $NC ::mhwd-tui::  "
    echo -e " ┌────────────────────────────────────────────────────────────────────────────┐"
    echo -e " │    1   Install Kernel                        2   Remove kernel             │"
    echo -e " │    3   Use free graphics                     4   Use nonfree graphics      │"
    echo -e " │    5   List installed drivers                                              │"    
    echo -e " └────────────────────────────────────────────────────────────────────────────┘"
    echo -e "          Select a number                       0 Exit mhwd-tui"
    echo ""
    read -s -n1 choix
    case $choix in
        1)
            echo
            install_kernel
            echo ""
            ;;
        2)
            echo
            remove_kernel
            echo ""
            ;;
        3)
            echo "installing free video-driver"
            echo ""
            sudo mhwd -a pci free 0300
            echo ""
            echo -e "Done. Press ${BLUE}[Enter]$NC to continue | ${BLUE}ctrl+c$NC to quit"
            read
            echo ""

            ;;
        4)
            echo "installing proprietary driver"
            echo ""
            sudo mhwd -a pci nonfree 0300
            echo ""
            echo -e "Done. Press ${BLUE}[Enter]$NC to continue | ${BLUE}ctrl+c$NC to quit"
            read
            echo ""
            ;;
        5)
            echo
            mhwd -li -d
            echo ""
            echo -e "Done. Press ${BLUE}[Enter]$NC to continue | ${BLUE}ctrl+c$NC to quit"
            read
            echo ""
            ;;

        0)
            clear && exit
            read
            ;;
        *)
            echo -e "$RED Wrong option $NC"
            echo ""
            echo "Wait and try again ..."
            echo ""
            sleep 2
            clear
            ;;
    esac
    done
fi
